default: &default
  adapter: postgresql
  pool: 100
  encoding: unicode

development:
  <<: *default
  database: <%= ENV['DEVELOPMENT_POSTGRES_DATABASE'] %>
  user:     <%= ENV['DEVELOPMENT_POSTGRES_USERNAME'] %>
  password: <%= ENV['DEVELOPMENT_POSTGRES_PASSWORD'] %>

test:
  <<: *default
  database: <%= ENV['TEST_POSTGRES_DATABASE'] %>
  user:     <%= ENV['TEST_POSTGRES_USERNAME'] %>
  password: <%= ENV['TEST_POSTGRES_PASSWORD'] %>

production:
  <<: *default
  database: <%= ENV['PROD_POSTGRES_DATABASE'] %>
  user:     <%= ENV['PROD_POSTGRES_USERNAME'] %>
  password: <%= ENV['PROD_POSTGRES_PASSWORD'] %>
